name: UnitTests

on:
  push:
    branches:
      - "feature/*"
      - "main"
  pull_request:
    types: [opened, synchronize]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.3.1.app

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Unit Tests
      run: |-
        #!/usr/bin/bash
        swift test --enable-code-coverage --verbose
        xcrun llvm-cov export -format="lcov" .build/debug/StoredInPackageTests.xctest/Contents/MacOS/StoredInPackageTests -instr-profile \
         .build/debug/codecov/default.profdata \
         > info.lcov 

    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./info.lcov
        flags: unittests
        fail_ci_if_error: true
        verbose: true
